### ISSUE TITLE
55 - Frontend fixes

### ISSUE THREAD

**Issue by sfwathen** [hack4impact-calpoly/equestrian-therapy#115]
This issue will consist of three frontend fixes on the mobile home page. 

First, fix the padding issue on the mobile weekly calendar in the file: `components/mobile/mobileWeeklyView.tsx`. This issue can be reproduced by clicking different dates on the weekly mobile calendar, you'll notice that the padding of the dates shifts whenever a new date is selected, however we would like for the dates to be static.  **PRIORITIZE THIS**

Second, add styling to match the figma for the dropdown toggle on the mobile home screen in the file: `components/mobile/dropdown.tsx`. 

Third, add cursor styling to the cursor when the user hovers over a timeslot on the weekly calendar so that it appears as a `pointer` (the hand with the finger pointing). 

This _may_ include:
* Familiarizing yourself with the dropdown code
* Messing around with things for a while

Checklist:
- [x] Make it look like the [Figma design](https://www.figma.com/file/OIkY5AHFB9xlkgDr7zHbqA/PET?type=design&node-id=1596-3899&t=v1k8HhNYUHwy5Uxm-0)
- [x] Fix the styling issue on the mobile weekly calendar, this will likely require messing around with the css for a while. All the dates should be evenly spaced
- [ ] Add styling to the dropdown menu on mobile, if possible, add the icons as shown on the figma as well. 
- [x] Make the cursor appear as a pointer when the user hovers over a timeslot on the weekly calendar
- [x] Use [styled-components](https://styled-components.com/docs/api) for styling

* this task may take very little time or a lot of time, let us know about the feasibility of the dropdown styling changes as it can be reconsidered.

**Comment by Lucif3r-in** [comment]
Can I work on this?
