### ISSUE TITLE
44 - Connect popup pages

### ISSUE THREAD

**Issue by borajoo** [hack4impact-calpoly/equestrian-therapy#95]
Connect the timeslot popup, timeslot confirmation popup, and timeslot success popup in the files: `components/popup/timeslotPopup.tsx`, `components/popup/timeslotConfirmation.tsx`, and `components/popup/timeslotSuccess.tsx`. 

This _may_ include:
* using the styled components PopupDiv and PopupBox from our `styledComponents.tsx`
* passing information to the TimeslotSuccess popup by props

Checklist:
- [x] Make the current TimeslotConfirmation and TimeslotSuccess components into popups (refer to TimeslotPopup for example)
- [x] Save/Book button on TimeslotPopup opens TimeslotConfirmation
- [x] Save/Book button on TimeslotConfirmation opens TimeslotSuccess
- [ ] Pass the fetched timeslots data to TimeslotConfirmation

**Comment by haysho2260** [comment]
To Do

- [ ] interpret selected dates as string
- [ ] interpret selected time as timeslot id
- [ ] pass back data from timeslots from what was selected
- [ ] update post functions to take in list of timeslot ids rather than list of dates
